version: '3.3'

services:
    db:
        restart: always
        volumes:
          - datadir:/data/db
    web:
        restart: always
        environment: 
            PORT: 3000
            HOST: '0.0.0.0'
        ports:
            - 3000:3000

volumes:
    datadir: {}